export const posts = [
  {
    id: 1,
    category: "Engineering",
    title: "My Journey Learning Fullstack JavaScript from Nepal",
    excerpt:
      "How I started coding with JavaScript, built real projects, and structured my learning path to become a professional software engineer.",
    author: "Dhiraj",
    avatar: "D",
    date: "Feb 14, 2026",
    readTime: "6 min read",
    featured: true,
    tags: ["JavaScript", "Learning Path", "Fullstack"],
  },
  {
    id: 2,
    category: "Backend",
    title: "Building My First Scalable Backend with Node.js and Express",
    excerpt:
      "Lessons learned from designing APIs, structuring folders, and handling real-world backend challenges.",
    author: "Dhiraj",
    avatar: "D",
    date: "Feb 12, 2026",
    readTime: "5 min read",
    featured: false,
    tags: ["Node.js", "Express", "Backend"],
  },
  {
    id: 3,
    category: "Frontend",
    title: "React Projects That Made Me Understand Real Frontend Engineering",
    excerpt:
      "From components to state management, this is how I built production-like React applications.",
    author: "Dhiraj",
    avatar: "D",
    date: "Feb 10, 2026",
    readTime: "7 min read",
    featured: false,
    tags: ["React", "Frontend", "Projects"],
  },
  {
    id: 4,
    category: "Database",
    title: "MongoDB for Beginners: What I Learned After Building CRUD Apps",
    excerpt:
      "Schema design, indexing, and mistakes I made while learning MongoDB in real projects.",
    author: "Dhiraj",
    avatar: "D",
    date: "Feb 8, 2026",
    readTime: "6 min read",
    featured: false,
    tags: ["MongoDB", "Database", "CRUD"],
  },
  {
    id: 5,
    category: "Career",
    title:
      "How I Stay Consistent Learning Software Engineering as a Student in Nepal",
    excerpt:
      "My daily routine, learning resources, and mindset hacks to stay disciplined.",
    author: "Dhiraj",
    avatar: "D",
    date: "Feb 6, 2026",
    readTime: "4 min read",
    featured: false,
    tags: ["Career", "Discipline", "Learning"],
  },
  {
    id: 6,
    category: "Git",
    title: "Git & GitHub Workflow I Use for All My Projects",
    excerpt:
      "Branching, commits, and collaboration practices that made my projects professional.",
    author: "Dhiraj",
    avatar: "D",
    date: "Feb 4, 2026",
    readTime: "5 min read",
    featured: false,
    tags: ["Git", "GitHub", "Workflow"],
  },
  {
    id: 7,
    category: "Engineering",
    title: "Structuring a Clean Backend Project with ESM Modules",
    excerpt:
      "Folder structure, environment variables, and scalable architecture using pure JavaScript.",
    author: "Dhiraj",
    avatar: "D",
    date: "Feb 2, 2026",
    readTime: "8 min read",
    featured: false,
    tags: ["Node.js", "ESM", "Architecture"],
  },
  {
    id: 8,
    category: "Productivity",
    title: "Tools That Boost My Productivity as a Student Developer",
    excerpt:
      "VS Code extensions, AI tools, and workflows that help me learn and build faster.",
    author: "Dhiraj",
    avatar: "D",
    date: "Jan 30, 2026",
    readTime: "4 min read",
    featured: false,
    tags: ["Tools", "Productivity", "VS Code"],
  },
  {
    id: 9,
    category: "Mindset",
    title: "Thinking Like a Software Engineer, Not Just a Student",
    excerpt:
      "How I shifted my mindset from tutorials to real engineering thinking and problem-solving.",
    author: "Dhiraj",
    avatar: "D",
    date: "Jan 28, 2026",
    readTime: "5 min read",
    featured: false,
    tags: ["Mindset", "Engineering", "Growth"],
  },
];

export const categories = [
  "All",
  "React",
  "Express",
  "Node",
  "MongoDB",
  "Git",
  "Career",
];
export const stats = [
  { num: "20+", label: "Projects Built" },
  { num: "500+", label: "Hours of Coding" },
  { num: "100+", label: "GitHub Commits" },
  { num: "∞", label: "Learning Journey" },
];